---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: projectcapsule
  namespace: flux-system
spec:
  type: "oci"
  interval: 5m0s
  url: oci://ghcr.io/projectcapsule/charts
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: capsule
  namespace: flux-system
spec:
  targetNamespace: capsule-system
  serviceAccountName: helm-controller
  install:
    createNamespace: true
  releaseName: capsule
  interval: 5m
  chart:
    spec:
      chart: capsule
      sourceRef:
        kind: HelmRepository
        name: projectcapsule
      interval: 1m
#---
# I'm quite sure this is not needed.
##
## Tenant GitOps Reconcilers identitiies need to
## reconcile Namespaces also with patch besides
## create, which is included by default by Capsule.
##
#apiVersion: rbac.authorization.k8s.io/v1
#kind: ClusterRole
#metadata:
#  name: capsule-namespace-provisioner-gitops
#rules:
#- apiGroups:
#  - ""
#  resources:
#  - namespaces
#  verbs:
#  - patch
#
