apiVersion: batch/v1
kind: Job
metadata:
  name: kubeconfig-generator
  namespace: daniel-home
spec:
  template:
    spec:
      serviceAccountName: kubeconfig-generator
      restartPolicy: Never
      containers:
      - image: ghcr.io/maxgio92/proxy-kubeconfig-generator:0.1.3
        name: kubeconfig-generator
        args:
        - --kubeconfig-secret-key=kubeconfig
        - --namespace=daniel-home
        - --serviceaccount=gitops-reconciler
        - --server=https://capsule-proxy.capsule-system.svc:9001
        - --server-tls-secret-namespace=capsule-system
        - --server-tls-secret-name=capsule-proxy
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: kubeconfig-generator
  namespace: daniel-home
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: kubeconfig-generator-daniel
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin # Do not do it in production! Please tailor a fine-grained role.
subjects:
- kind: ServiceAccount
  name: kubeconfig-generator
  namespace: daniel-home
