---
apiVersion: capsule.clastix.io/v1beta2
kind: Tenant
metadata:
  name: news
spec:
  additionalRoleBindings:
  - clusterRoleName: cluster-admin
    subjects:
    - name: gitops-reconciler
      kind: ServiceAccount
      namespace: news-home
  owners:
  - name: system:serviceaccount:news-home:gitops-reconciler
    kind: ServiceAccount
---
apiVersion: v1
kind: Namespace
metadata:
  labels:
    capsule.clastix.io/tenant: news
  name: news-home